theme: jekyll-theme-cayman

title: Ошибки в писанине Катющика
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nauka1.ru" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
